// src/app/api/cron/billing/route.ts
import { NextResponse } from 'next/server';
import prisma from '@/lib/db';

function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

function advanceBillingDate(current: Date, cycle: string): Date {
  switch (cycle) {
    case 'MONTHLY':
      return addMonths(current, 1);
    case 'QUARTERLY':
      return addMonths(current, 3);
    case 'SEMI_ANNUALLY':
      return addMonths(current, 6);
    case 'ANNUALLY':
      return addMonths(current, 12);
    default:
      return addMonths(current, 1);
  }
}

export async function GET(request: Request) {
  // Security: validate Authorization header against CRON_SECRET
  const authHeader = request.headers.get('Authorization');
  const cronSecret = process.env.CRON_SECRET;

  if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const now = new Date();

  // Step 1: Fetch all active subscriptions whose billing date is due
  const dueSubscriptions = await prisma.clientSubscription.findMany({
    where: {
      isActive: true,
      nextBillingDate: { lte: now },
    },
    include: {
      client: { select: { id: true, businessName: true } },
      service: { select: { id: true, name: true } },
    },
  });

  if (dueSubscriptions.length === 0) {
    return NextResponse.json({ generated: 0, invoices: [] });
  }

  // Step 2: Batch process all subscriptions in a single transaction for atomicity
  const results: Array<{
    subscriptionId: number;
    invoiceNumber: string;
    clientId: number;
  }> = [];
  const errors: Array<{ subscriptionId: number; error: string }> = [];

  try {
    await prisma.$transaction(async (tx) => {
      // Generate invoice numbers sequentially within transaction to prevent collisions
      const year = now.getFullYear();
      const prefix = `INV-${year}-`;

      const latest = await tx.invoice.findFirst({
        where: { invoiceNumber: { startsWith: prefix } },
        orderBy: { invoiceNumber: 'desc' },
        select: { invoiceNumber: true },
      });

      let nextSeq = 1;
      if (latest) {
        const parts = latest.invoiceNumber.split('-');
        const lastSeq = parseInt(parts[parts.length - 1]!, 10);
        if (!isNaN(lastSeq)) nextSeq = lastSeq + 1;
      }

      const monthYear = now.toLocaleDateString('en-PH', {
        month: 'long',
        year: 'numeric',
      });

      const dueDate = new Date(now);
      dueDate.setDate(dueDate.getDate() + 15);

      // Process all subscriptions in batch
      for (const sub of dueSubscriptions) {
        const invNumber = `${prefix}${String(nextSeq).padStart(4, '0')}`;
        nextSeq++;

        const agreedRate = Number(sub.agreedRate);

        // Create invoice
        const invoice = await tx.invoice.create({
          data: {
            invoiceNumber: invNumber,
            clientId: sub.clientId,
            status: 'UNPAID',
            issueDate: now,
            dueDate,
            subTotal: agreedRate,
            taxAmount: 0,
            discountAmount: 0,
            totalAmount: agreedRate,
            balanceDue: agreedRate,
            notes: `Auto-generated billing for ${monthYear}`,
          },
        });

        // Create invoice line item
        await tx.invoiceItem.create({
          data: {
            invoiceId: invoice.id,
            description: `${sub.service.name} \u2014 ${monthYear}`,
            quantity: 1,
            unitPrice: agreedRate,
            total: agreedRate,
          },
        });

        // Log invoice creation
        await tx.invoiceHistory.create({
          data: {
            invoiceId: invoice.id,
            actorId: null,
            changeType: 'INVOICE_CREATED',
            newValue: `Auto-generated by billing cron for subscription #${sub.id}`,
          },
        });

        // Advance next billing date
        const currentBillingDate = sub.nextBillingDate ?? now;
        const newNextBillingDate = advanceBillingDate(currentBillingDate, sub.billingCycle);

        await tx.clientSubscription.update({
          where: { id: sub.id },
          data: { nextBillingDate: newNextBillingDate },
        });

        results.push({
          subscriptionId: sub.id,
          invoiceNumber: invNumber,
          clientId: sub.clientId ?? 0,
        });
      }
    });
  } catch (err) {
    console.error('[cron/billing] Batch transaction failed:', err);
    errors.push({ subscriptionId: 0, error: String(err) });
  }

  // Step 3: Return summary
  return NextResponse.json({
    generated: results.length,
    invoices: results,
    ...(errors.length > 0 && { errors }),
  });
}
